#CREDITS TO @muchobien

name: Relase on pocketbase/release
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest pocketbase version
        id: pocketbase
        uses: augustodelg/repo-get-releases@main
        with:
          repository: pocketbase/pocketbase
          excludes: draft,prerelease

      - name: Checkout code
        uses: actions/checkout@v1
          
      - name: Read file contents
        id: set_processed_version
        run: |
          version=`cat ./version`
          echo "::set-output name=processed_version::$version"
            
      - name: Cancel if there is no changes
        if: ${{ steps.pocketbase.outputs.version == steps.set_processed_version.outputs.processed_version && github.event_name != 'workflow_dispatch' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Version already released')
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: docker.hub
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PASS_SECRET }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            augustodelg/pocketbase-action-test
          tags: |
            type=semver,pattern={{version}},value=${{ steps.pocketbase.outputs.version }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: POCKETBASE_VERSION=${{ steps.pocketbase.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
